# Generated by Django 3.0.2 on 2020-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Поддомен маленькими буквами (например, msk)')),
                ('town', models.CharField(max_length=30, null=True, verbose_name='Город (например, Москва)')),
                ('townAlias', models.CharField(max_length=30, null=True, verbose_name='Склонение города (должно отвечать на вопрос ГДЕ, например, Москве)')),
            ],
            options={
                'verbose_name': 'Поддомен',
                'verbose_name_plural': 'Поддомены',
            },
        ),
    ]
