# Generated by Django 3.0.2 on 2020-01-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название категории')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='category_img/', verbose_name='Изображение категории')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать категорию ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Основная категория',
                'verbose_name_plural': 'Основные категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item/', verbose_name='Картинка')),
                ('text1', models.TextField(blank=True, null=True, verbose_name='Краткое описание товара (отображается в карточке товара)')),
                ('text2', models.TextField(blank=True, null=True, verbose_name='Краткое описание товара (отображается в карточке товара)')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
