# Generated by Django 3.0.2 on 2020-03-24 15:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200109_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO текст'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1'),
        ),
    ]
