# Generated by Django 3.0.2 on 2020-03-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200324_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
