# Generated by Django 3.0.2 on 2020-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_category_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Инструкция'),
        ),
    ]
