# Generated by Django 3.0.2 on 2020-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new_price',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='Старая цена'),
        ),
    ]
