# Generated by Django 2.2.7 on 2020-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_item_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_text',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. текст'),
        ),
    ]
