# Generated by Django 2.2.7 on 2020-07-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_item_add_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-order_num',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='item',
            name='order_num',
            field=models.IntegerField(default=100, verbose_name='Порядок'),
        ),
    ]
