# Generated by Django 3.0.2 on 2020-07-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20200703_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('order_num',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
