# Generated by Django 3.0.2 on 2020-07-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Доки'),
        ),
    ]
